name: CI-CD

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

  CD:
    runs-on: ubuntu-latest

    needs: [CI]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.,!node_modules'
          target: '~/apps/gerador-de-dados'

      - name: Run script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/gerador-de-dados
            yarn
