name: CI-CD

on:
  push:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Exclude node_modules and upload build artifact
        run: |
          tar --exclude='./node_modules' -czf project.tar.gz .

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.4.3
        with:
          name: project-artifacts
          path: project.tar.gz

  CD:
    runs-on: ubuntu-latest

    needs: [CI]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Download build artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: project-artifacts
          path: ./downloaded_artifacts

      - name: Extract the artifact
        run: |
          tar -xzf ./downloaded_artifacts/project.tar.gz -C ./downloaded_artifacts

      - name: Deploy to server via SCP
        run: |
          scp -r ./downloaded_artifacts/* ${{ secrets.HOST_USER }}@${{ secrets.HOST_SERVER }}:${{ secrets.HOST_PATH }}
