name: CI-CD

on:
  push:
    branches: [branch-name]

jobs:
  CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: mock
          POSTGRES_PASSWORD: mock_password
          POSTGRES_DB: mock_db

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h 127.0.0.1 -p 5432 -U mock; then
              echo "PostgreSQL is ready";
              exit 0;
            fi;
            echo "Waiting for PostgreSQL...";
            sleep 5;
          done;
          exit 1

      - name: Wait for Redis to be ready
        run: |
          for i in {1..10}; do
            if echo PING | nc -w 1 127.0.0.1 6379 | grep PONG; then
              echo "Redis is ready";
              exit 0;
            fi;
            echo "Waiting for Redis...";
            sleep 5;
          done;
          exit 1

      - name: Run Prisma Migrations
        env:
          DATABASE_URL: 'postgresql://mock:mock_password@127.0.0.1:5432/mock_db'
        run: npx prisma migrate deploy

      - name: Run tests
        env:
          DATABASE_URL: 'postgresql://mock:mock_password@127.0.0.1:5432/mock_db'
          REDIS_HOST: '127.0.0.1'
          REDIS_PORT: '6379'
          REDIS_PASSWORD: ''
          REDIS_DB: '0'
          NODE_ENV: 'test'
          MAIL_HOST: 'smtp-relay.sendinblue.com'
          MAIL_PORT: '587'
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
          MAIL_ADDRESS: 'noreply@teste.com'
          MAIL_NAME: 'Mock test'
          CI_RUN: 'true'
        run: yarn test

  CD:
    runs-on: ubuntu-latest

    needs: [CI]

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20.15.1

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run build
        run: yarn build

      - name: Copy to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST_SERVER}}
          username: ${{ secrets.HOST_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: '.,!node_modules'
          target: '~/apps/project-name'

      - name: Run script on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_SERVER }}
          username: ${{ secrets.HOST_USER }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/apps/project-name'
            yarn
            yarn prisma migrate deploy
            pm2 restart project-name'
